# MythicChanger by @PQguanfang
#
# Read the Wiki here: https://mythicchanger.superiormc.cn/

real-change-trigger:
  SetSlotTrigger:
    enabled: true
  InventoryClickEvent:
    enabled: true

# Some change rules do not support real change perfectly.
# For example, add-name-first rule require you also set contains-name rule.
# Otherwise, each time you interact with this item, the name of it will have additional content added due to this rule.
# Like: 'Good Good Good Good Good Diamond Sword' if you set add-name-first: 'Good' and interact with this item 5 times.
bypass-real-change-limit: false

# Premium version only
apply-items:
  A:
    material: PAPER
    name: '&fItem Skin &8(Diamond Sword)'
    lore:
      - '&7Drag this item onto the item you want to apply.'
    apply-rule: default
    # After apply real change, the item can no longer be rollback.
    apply-real-change: false
    match-item:
      items:
        - 'diamond_sword'
  B:
    material: BOOK
    name: '&fRollback book'
    lore:
      - '&7Drag this item onto the item you want to rollback its apply.'
    apply-rule: deapply # This means deapply, not rule ID.