name: MythicChanger
version: '${project.version}'
main: cn.superiormc.mythicchanger.MythicChanger
api-version: '1.14'
author: PQguanfang
depend:
  - ProtocolLib
softdepend:
  - EcoItems
  - EcoArmor
  - MythicMobs
  - MMOItems
  - NeigeItems
  - ItemsAdder
  - Oraxen
  - ExecutableItems
commands:
  mythicchanger:
    aliases:
      - "mc"
      - "mchanger"
    usage: "/mythicchanger"
    description: "MythicChanger Main Command."