name: MythicChanger
version: '${project.version}'
main: cn.superiormc.mythicchanger.MythicChanger
api-version: '1.14'
folia-supported: true
author: PQguanfang
depend:
  - packetevents
softdepend:
  - EcoItems
  - EcoArmor
  - MythicMobs
  - MMOItems
  - NeigeItems
  - ItemsAdder
  - Oraxen
  - ExecutableItems
  - NBTAPI
  - eco
  - QuickShop-Hikari
  - InteractiveChat
  - TrChat
commands:
  mythicchanger:
    aliases:
      - "mc"
      - "mchanger"
    usage: "/mythicchanger"
    description: "MythicChanger Main Command."